# Generated by Django 4.2 on 2024-09-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_author_alter_blog_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "blog", "verbose_name_plural": "blogs"},
        ),
    ]
