# Generated by Django 4.2 on 2024-09-26 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_date", models.DateTimeField(verbose_name="arrival_date")),
                ("departure_date", models.DateTimeField(verbose_name="departure_date")),
                (
                    "total_price",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Total price",
                    ),
                ),
                (
                    "booking_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Active"), (0, "Inactive")],
                        default=0,
                        null=True,
                        verbose_name="Booking status",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
