# Generated by Django 4.2 on 2024-09-26 11:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="city"
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="name"
                    ),
                ),
                (
                    "hotel_star_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "One star"),
                            (2, "Two stars"),
                            (3, "Three stars"),
                            (4, "Four stars"),
                            (5, "Five stars"),
                        ],
                        null=True,
                        verbose_name="star rating",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="address"
                    ),
                ),
                (
                    "hotel_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/img/hotel",
                        verbose_name="hotel_photo",
                    ),
                ),
                (
                    "number_of_rooms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="number of rooms"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="website"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "client_reviews",
                    models.TextField(
                        blank=True, null=True, verbose_name="client reviews"
                    ),
                ),
            ],
        ),
    ]
