# Generated by Django 4.2 on 2024-09-26 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="name"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="hotel",
            options={"verbose_name": "hotel", "verbose_name_plural": "hotels"},
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="room number",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SGL", "Single"),
                            ("DBL", "Double"),
                            ("TWN", "Twin"),
                            ("STU", "Studio"),
                            ("APT", "Apartment"),
                            ("DEL", "Deluxe"),
                            ("FAM", "Family"),
                            ("OFF", "Office"),
                        ],
                        max_length=120,
                        null=True,
                        verbose_name="room type",
                    ),
                ),
                (
                    "room_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        max_length=120,
                        null=True,
                        verbose_name="room status",
                    ),
                ),
                (
                    "price_per_night",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="price per night",
                    ),
                ),
                (
                    "floor",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="floor",
                    ),
                ),
                (
                    "room_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="room description"
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        related_name="amenities", to="hotels.amenity"
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        ),
        migrations.AddField(
            model_name="hotel",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hotels.room"
            ),
        ),
    ]
