# Generated by Django 4.2 on 2024-10-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_amenity_alter_hotel_options_room_hotel_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.room",
            ),
        ),
    ]
