# Generated by Django 4.2 on 2024-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_alter_hotel_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="room",
        ),
        migrations.AddField(
            model_name="hotel",
            name="room",
            field=models.ManyToManyField(blank=True, null=True, to="hotels.room"),
        ),
    ]
